### ISSUE TITLE
Convert ava tests so they work in-browser and on node and on the built distributions

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/memory-fs#5]
Currently the ava tests only run against the source.

The tests don't run on the built distributions. And in the case of the browser target, it should be tested within a browser environment.

**Comment by CMCDragonkai** [comment]
For a quick import test of the browser target:

```
 <html>
   <head>
     <meta charset="UTF-8">
     <title>test</title>
     <script type="text/javascript" src="./dist/index.browser.umd.js"></script>
   </head>
   <body>
     <p>test</p>
   </body>
 </html>
```

And save and load it as index.html.

**Comment by robert-cronin** [comment]
Does this still hold now that we are using jest to test?

**Comment by CMCDragonkai** [comment]
This is not important anymore. So I'm going to close it.
